# Usa uma imagem base do Python
FROM python:3.9-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o arquivo carguru.py para o diretório de trabalho do container
COPY carguru.py .

# Comando para executar o script Python
CMD ["python", "carguru.py"]
