# Usa uma imagem base do Python
FROM python:3.9-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o script Python para o diretório de trabalho dentro do container
COPY teste.py .

# Comando para executar o script Python
CMD ["python", "teste.py"]

# docker build -t mascarar-dados .  // comando para fazer a build do container
# docker run -it mascarar-dados // comando para rodar o container